import test from 'node:test';import assert from 'node:assert/strict';import {researchPublicCompany,ProviderError} from '../server/providers/sec.mjs';import {generateInitialModel,safeNumber} from '../server/model.mjs';
const submissions={cik:320193,name:'Apple Inc.',tickers:['AAPL'],exchanges:['Nasdaq'],sic:'3571',sicDescription:'Electronic Computers',stateOfIncorporationDescription:'California',addresses:{business:{city:'Cupertino',stateOrCountryDescription:'CA',zipCode:'95014'}}};
const unit=(val,concept)=>({label:concept,units:{USD:[{val,fy:2024,fp:'FY',form:'10-K',filed:'2024-11-01',start:'2023-10-01',end:'2024-09-28',accn:'0000320193-24-000123'}]}});
const facts={facts:{'us-gaap':{RevenueFromContractWithCustomerExcludingAssessedTax:unit(391035000000,'Revenue'),OperatingIncomeLoss:unit(123216000000,'Operating income'),CashAndCashEquivalentsAtCarryingValue:unit(29943000000,'Cash')}}};
const fetcher=async url=>({ok:true,json:async()=>url.includes('companyfacts')?facts:submissions});
test('real-company SEC path resolves identity, cited claims, and initial model',async()=>{const result=await researchPublicCompany('AAPL',{fetcher,now:new Date('2026-09-06T12:00:00Z')});assert.equal(result.identity.legalName,'Apple Inc.');assert.equal(result.identity.ticker,'AAPL');assert.equal(result.identity.country,'United States');assert.equal(result.identity.location,'Cupertino, CA, United States');assert(result.evidence.claims.every(x=>x.sourceUrl.startsWith('https://www.sec.gov/Archives/')));assert(result.evidence.claims.every(x=>x.provenance==='Reported'));const model=generateInitialModel(result);assert.equal(model.checks[0].status,'pass');assert(model.outputs.some(x=>x.id==='operating-margin'));const revenue=model.outputs.find(x=>x.id==='base-revenue');assert.equal(revenue.low,revenue.value);assert.equal(revenue.high,revenue.value);const marketCap=model.outputs.find(x=>x.id==='market-cap');assert(marketCap.low>0&&marketCap.high>marketCap.low);assert.equal(marketCap.provenance,'Model-estimated');});
test('provider failure is honest and carries a next action',async()=>{await assert.rejects(()=>researchPublicCompany('AAPL',{fetcher:async()=>{throw new Error('offline')}}),e=>e instanceof ProviderError&&e.code==='NETWORK_UNAVAILABLE'&&e.nextAction.includes('retry'));});
test('input validation rejects false precision states',()=>{assert.deepEqual(safeNumber('NaN',{label:'Growth'}),{ok:false,error:'Growth must be a finite number.'});assert.equal(safeNumber('12.5',{min:0,max:100}).value,12.5);});
test('SEC facts choose the newest reporting period rather than a newly filed comparison',async()=>{const comparison={facts:{'us-gaap':{RevenueFromContractWithCustomerExcludingAssessedTax:{label:'Revenue',units:{USD:[{val:100,fy:2025,fp:'FY',form:'10-K',filed:'2025-10-31',start:'2022-01-01',end:'2022-12-31',accn:'old'},{val:140,fy:2025,fp:'FY',form:'10-K',filed:'2025-10-31',start:'2024-01-01',end:'2024-12-31',accn:'new'}]}}}}};const localFetch=async url=>({ok:true,json:async()=>url.includes('companyfacts')?comparison:submissions});const result=await researchPublicCompany('AAPL',{fetcher:localFetch});assert.equal(result.evidence.claims[0].value,140);assert.equal(result.evidence.claims[0].periodEnd,'2024-12-31');});
