import fs from 'node:fs';import path from 'node:path';import {generateInitialModel} from './model.mjs';
const refreshPlan=workspace=>{workspace.plan=(workspace.plan||[]).map(item=>{if(item.id==='market')return{...item,label:'Estimate current market capitalization',status:'ready',reason:'No live market-data provider is configured.',nextAction:'Groundline uses reported fundamentals and a visible multiple range until price data is available.'};if(!workspace.identity?.cik&&item.id==='financials')return{...item,label:'Estimate unavailable company financials',status:'ready',reason:'Private companies do not publish standardized SEC company facts.',nextAction:'Groundline starts with broad ranges and replaces them as better evidence is added.'};if(!workspace.identity?.cik&&item.id==='model')return{...item,label:'Generate range-based model',status:'ready',reason:'Low-confidence estimates remain visibly labeled and traceable.',nextAction:'Add financial evidence to narrow the ranges.'};return item;});return workspace;};
export class LocalStore{
 constructor(file=process.env.GROUNDLINE_DATA_PATH||'.groundline/data.json'){this.file=path.resolve(file);fs.mkdirSync(path.dirname(this.file),{recursive:true});if(!fs.existsSync(this.file))this.write({version:1,workspaces:[],audit:[]});}
 read(){return JSON.parse(fs.readFileSync(this.file,'utf8'));}
 write(data){const tmp=`${this.file}.tmp`;fs.writeFileSync(tmp,JSON.stringify(data,null,2),{mode:0o600});fs.renameSync(tmp,this.file);}
 saveResearch(result,objective){const db=this.read(),key=result.identity.cik||result.identity.legalName.toLowerCase().replace(/[^a-z0-9]+/g,'-'),id=`ws-${key}`;const existing=db.workspaces.find(x=>x.id===id);const workspace={id,kind:result.identity.cik?'live-research':'private-research',objective,createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),...result};const i=db.workspaces.findIndex(x=>x.id===id);if(i<0)db.workspaces.push(workspace);else db.workspaces[i]=workspace;db.audit.push({id:`audit-${Date.now()}`,workspaceId:id,action:'research.completed',at:workspace.updatedAt,actor:result.evidence.provider});this.write(db);return workspace;}
 get(id){const workspace=this.read().workspaces.find(x=>x.id===id)||null;if(workspace){workspace.model=generateInitialModel(workspace);refreshPlan(workspace);}return workspace;}
 addManualClaim(id,input){const db=this.read(),workspace=db.workspaces.find(x=>x.id===id);if(!workspace)return null;const value=Number(input.value);if(!Number.isFinite(value))throw new Error('Manual values must be finite numbers.');const claim={id:`manual-${Date.now()}`,companyId:workspace.identity.cik||id,metricId:String(input.label).toLowerCase().replace(/[^a-z0-9]+/g,'-'),label:String(input.label).trim(),value,unit:input.unit||'USD',currency:input.unit==='USD'?'USD':null,periodStart:null,periodEnd:input.periodEnd||null,sourceUrl:null,sourceTitle:'Manual entry',sourceType:'User-provided evidence',retrievedAt:new Date().toISOString(),location:String(input.rationale).trim(),excerpt:null,confidence:0.7,provenance:'User-entered',usedInModel:true};workspace.evidence.claims.push(claim);workspace.model=generateInitialModel(workspace);refreshPlan(workspace);workspace.updatedAt=new Date().toISOString();db.audit.push({id:`audit-${Date.now()}`,workspaceId:id,action:'claim.added',claimId:claim.id,at:workspace.updatedAt,actor:'Local user'});this.write(db);return workspace;}
 list(){return this.read().workspaces.map(({evidence,...x})=>({...x,claimCount:evidence?.claims?.length||0}));}
}
