const SEC='https://data.sec.gov';
const ARCHIVES='https://www.sec.gov/Archives/edgar/data';
export class ProviderError extends Error { constructor(code,message,nextAction){super(message);this.code=code;this.nextAction=nextAction;} }
const headers=()=>({'User-Agent':process.env.SEC_USER_AGENT||'Groundline local research contact@example.com','Accept-Encoding':'gzip, deflate','Accept':'application/json'});
async function json(url,fetcher=fetch){let res;try{res=await fetcher(url,{headers:headers()});}catch{throw new ProviderError('NETWORK_UNAVAILABLE','SEC EDGAR could not be reached.','Check your connection and retry; no invented data was substituted.');}if(!res.ok)throw new ProviderError(res.status===429?'RATE_LIMITED':'PROVIDER_ERROR',`SEC EDGAR returned HTTP ${res.status}.`,res.status===429?'Wait and retry; SEC rate limits are respected.':'Check SEC_USER_AGENT and retry.');return res.json();}
export async function resolveCompany(query,fetcher=fetch){const data=await json(`${SEC}/submissions/CIK0000320193.json`.replace('0000320193', query.match(/^\d+$/)?query.padStart(10,'0'):'0000320193'),fetcher);const q=query.trim().toUpperCase();if(q && !/^AAPL|APPLE|320193|0000320193$/.test(q)){const tickers=await json('https://www.sec.gov/files/company_tickers.json',fetcher);const match=Object.values(tickers).find(x=>x.ticker?.toUpperCase()===q||x.title?.toUpperCase().includes(q));if(!match)throw new ProviderError('NO_MATCH',`No SEC registrant matched “${query}”.`,'Try a U.S. ticker or exact legal name; private companies may require document upload.');return resolveCompany(String(match.cik_str),fetcher)}
 return {cik:String(data.cik).padStart(10,'0'),legalName:data.name,ticker:data.tickers?.[0]||null,exchange:data.exchanges?.[0]||null,country:data.addresses?.business?.stateOrCountryDescription||data.stateOfIncorporationDescription||'United States',sector:data.sicDescription||'Not classified',sic:data.sic,confidence:q===data.tickers?.[0]?.toUpperCase()?0.99:0.94,sourceUrl:`${SEC}/submissions/CIK${String(data.cik).padStart(10,'0')}.json`};}
const concepts=[['RevenueFromContractWithCustomerExcludingAssessedTax','Revenue'],['Revenues','Revenue'],['NetIncomeLoss','Net income'],['Assets','Total assets'],['CashAndCashEquivalentsAtCarryingValue','Cash and cash equivalents'],['StockholdersEquity','Stockholders equity'],['OperatingIncomeLoss','Operating income']];
export async function collectCompanyFacts(identity,fetcher=fetch,now=new Date()){const data=await json(`${SEC}/api/xbrl/companyfacts/CIK${identity.cik}.json`,fetcher);const claims=[];const seen=new Set();for(const [concept,label] of concepts){const fact=data.facts?.['us-gaap']?.[concept];if(!fact)continue;const units=fact.units?.USD||fact.units?.shares||[];const rows=units.filter(x=>x.form==='10-K'||x.form==='10-Q').sort((a,b)=>String(b.filed).localeCompare(String(a.filed)));const latest=rows.find(x=>x.fp==='FY')||rows[0];if(!latest||seen.has(label))continue;seen.add(label);claims.push({id:`sec-${concept}-${latest.accn}-${latest.end}`,companyId:identity.cik,metricId:concept,label,value:latest.val,unit:fact.units?.USD?'USD':Object.keys(fact.units||{})[0],currency:fact.units?.USD?'USD':null,periodStart:latest.start||null,periodEnd:latest.end,form:latest.form,filingDate:latest.filed,accession:latest.accn,sourceUrl:`${ARCHIVES}/${Number(identity.cik)}/${latest.accn.replaceAll('-','')}/${latest.accn}-index.html`,sourceTitle:`${identity.legalName} ${latest.form} filed ${latest.filed}`,sourceType:'SEC filing',retrievedAt:now.toISOString(),location:`XBRL us-gaap:${concept}`,excerpt:null,confidence:0.99,provenance:'Reported',usedInModel:['Revenue','Operating income'].includes(label)});}
return {provider:'SEC EDGAR',providerUrl:'https://www.sec.gov/edgar/sec-api-documentation',retrievedAt:now.toISOString(),claims};}
export async function researchPublicCompany(query,{fetcher=fetch,now=new Date()}={}){const identity=await resolveCompany(query,fetcher);const evidence=await collectCompanyFacts(identity,fetcher,now);return {identity,evidence,plan:[{id:'identity',label:'Resolve legal entity',status:'complete'},{id:'filings',label:'Collect SEC submissions and company facts',status:'complete'},{id:'claims',label:'Normalize reported financial claims',status:'complete'},{id:'market',label:'Obtain current market capitalization',status:'blocked',reason:'No market-data provider configured',nextAction:'Set MARKET_DATA_PROVIDER and its local API key.'},{id:'model',label:'Generate evidence-backed operating model',status:evidence.claims.some(x=>x.label==='Revenue')?'ready':'blocked'}]};}
